blank_issues_enabled: false
contact_links:
  - name: sts2levelqs.jl package support
    url: https://github.com/dtinas10/sts2levelqs.jl/discussions
    about: Please ask and answer questions about sts2levelqs.jl here.
  - name: dtinas10 organisation support
    url: https://github.com/orgs/dtinas10/discussions
    about: For more general questions about dtinas10 ecosystem it's here.
