[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OptimalControl = "29ba98a3-5749-4881-8b3e-bf35da58c9d8"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c1-2e2d8b2b47f0"
NLPModelsIpopt = "f889c8d9-9b33-50d3-ac8e-6d28f3b5a23a"
MINPACK = "82899510-4779-5014-852e-03e436cf321d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
Documenter = "1"
